#!/bin/bash

[ $(uname -s) = "Darwin" ] && export MACOS=1
[ $(uname -s) = "Linux" ] && export LINUX=1

cd $HOME

# oh-my-zsh
sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

# zsh-autosuggestions
git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions

if [ $MACOS ]
then
  # homebrew
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

  # Install packages
  mv .Brewfile Brewfile
  brew bundle
elif [ $LINUX ]
then
  packages=(
    fzf
    git
    kitty
    rbenv
    zsh
    vim
  )
  # Arch
  if command -v pacman &> /dev/null
  then
    packages+=(otf-hasklig starship)
    pacman -S git base-devel

    # Install YaY
    git clone https://aur.archlinux.org/yay.git
    cd yay
    makepkg -si
    cd ..
    rm -rf yay

    for package in "${packages[@]}"
    do
      yay -Sy $package
    done
  elif command -v apt &> /dev/null
  then
    for package in "${packages[@]}"
    do
      apt install -y $package
    done

    # starship
    FORCE=1 sh -c "$(curl -fsSL https://starship.rs/install.sh)"
  else
    echo "I don't know how to install packages on your system."
  fi
fi

$(dirname $0)/install-vscode-extensions
